In [1]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [5]:
match = pd.read_csv(r"C:\Users\Aditya kumar Dubey\OneDrive\Documents\Desktop\Data\matches.csv")
delivery = pd.read_csv(r"C:\Users\Aditya kumar Dubey\OneDrive\Documents\Desktop\Data\deliveries.csv")

ipl = delivery.merge(match,left_on='match_id',right_on= 'id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

**1. Scatter Plot**

In [6]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date', 'team1',
       'team2', 'toss_winner', 'toss_decision', 'result', 'dl_applied',
       'winner', 'win_by_runs', 'win_by_wickets', 'player_of_match', 'venue',
       'umpire1', 'umpire2', 'umpire3'],
      dtype='object')

In [22]:
top50 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending = False).head(50).index.tolist()
new_ipl = ipl[ipl['batsman'].isin(top50)]

In [23]:
#clalulation stric rate
runs = new_ipl.groupby('batsman')['batsman_runs'].sum()
balls = new_ipl.groupby('batsman')['batsman_runs'].count()
sr = (runs/balls)*100
sr = sr.reset_index()
sr

             batsman  batsman_runs
0     AB de Villiers    145.129059
1       AC Gilchrist    133.054662
2           AJ Finch    126.299213
3          AM Rahane    117.486549
4          AT Rayudu    123.014257
5        BB McCullum    126.318203
6           BJ Hodge    121.422376
7           CH Gayle    144.194313
8          DA Miller    137.709251
9          DA Warner    138.318401
10          DJ Bravo    122.286822
11         DJ Hussey    120.072661
12  DPMD Jayawardene    118.791064
13          DR Smith    132.279534
14      F du Plessis    124.161074
15         G Gambhir    120.361200
16        GJ Maxwell    157.564103
17         JH Kallis    105.936272
18         JP Duminy    121.970624
19        KA Pollard    140.621266
20     KC Sangakkara    118.469101
21        KD Karthik    123.008475
22           KK Nair    124.650161
23           M Vijay    120.028681
24        MEK Hussey    119.963592
25         MK Pandey    116.938453
26         MK Tiwary    114.127424
27          MS Dhoni    132.835821
28           NV Ojha    114.528024
29          PA Patel    112.718447
30          R Dravid    113.347237
31         RA Jadeja    118.792867
32         RG Sharma    128.497251
33        RV Uthappa    127.635135
34       S Badrinath    115.742972
35          S Dhawan    118.502496
36        SC Ganguly    101.734540
37          SE Marsh    130.109775
38          SK Raina    134.995548
39         SPD Smith    128.507127
40      SR Tendulkar    114.187867
41         SR Watson    134.838379
42         SS Tiwary    114.851485
43         SV Samson    122.403433
44        TM Dilshan    110.124164
45           V Kohli    126.588437
46          V Sehwag    148.827059
47           WP Saha    127.727646
48         YK Pathan    140.751445
49      Yuvraj Singh    126.390244